<tsd:PluginWindowBase x:Class="NgdPluginZeeConnect.NgdPluginZeeConnect"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             xmlns:ngdDialog="clr-namespace:Ngd.Dialog;assembly=Ngd.Dialog"
             xmlns:fui="http://schemas.trimble.com/fusion"
			 xmlns:local="clr-namespace:NgdPluginZeeConnect"
             mc:Ignorable="d" 
             Title="NgdPluginZeeConnect"
             d:DesignHeight="435" d:DesignWidth="565"
               MinHeight="435" MinWidth="565">
    <d:UserControl.DataContext>
        <local:NgdPluginZeeConnectViewModel />
    </d:UserControl.DataContext>
    <Window.InputBindings>
        <KeyBinding Command="Help" Key="F1"/>
    </Window.InputBindings>
    <Window.CommandBindings>
        <CommandBinding Command="ApplicationCommands.Help" Executed="HelpExecuted" />
    </Window.CommandBindings>
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Fusion;component/Themes/Generic.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <local:EnumImageConverter x:Key="ImageConverter"/>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad x:Name="SaveLoad" HelpKeyword="NgdTeklaTools\NgdPluginZeeConnect" />
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="2"
            ApplyClicked="WpfOkApplyModifyGetOnOffCancel_ApplyClicked"
            OkClicked="WpfOkApplyModifyGetOnOffCancel_OkClicked"
            ModifyClicked="WpfOkApplyModifyGetOnOffCancel_ModifyClicked"
            GetClicked="WpfOkApplyModifyGetOnOffCancel_GetClicked"
            OnOffClicked="WpfOkApplyModifyGetOnOffCancel_OnOffClicked"
            CancelClicked="WpfOkApplyModifyGetOnOffCancel_CancelClicked"/>
        <TabControl Grid.Row="1">
            <TabItem Header="General">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto" />
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                    </Grid.RowDefinitions>

                    <Label Content="Display Text" VerticalAlignment="Center" />
                    <StackPanel Grid.Column="1" Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="DisplayText"/>
                        <TextBox TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center"
                                 Text="{Binding DisplayText, Mode=TwoWay}"
                                 fui:Extensions.Watermark="{Binding DisplayTextWatermark}"/>
                    </StackPanel>

                    <Label Content="Profile" Grid.Row="1" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="1" Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="MyProfile" />
                        <TextBox TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding MyProfile, Mode=TwoWay}"
								 fui:Extensions.Watermark="Select Profile"/>
                        <UIControls:WpfProfileCatalog Name="MyProfileCatalog" 
							                          VerticalAlignment="Center"
							                          SelectClicked="MyProfileCatalog_SelectClicked"
							                          SelectionDone="MyProfileCatalog_SelectionDone"/>
                    </StackPanel>

                    <Label Content="Shape" Grid.Row="2" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="2" Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="MyShape" />
                        <TextBox TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding MyShape, Mode=TwoWay}"
								 fui:Extensions.Watermark="Select Shape"/>
                        <UIControls:WpfShapeCatalog VerticalAlignment="Center"
                                                    Name="MyShapeCatalog"
                                                    SelectClicked="MyShapeCatalog_SelectClicked"
                                                    SelectionDone="MyShapeCatalog_SelectionDone"/>
                    </StackPanel>

                    <Label Content="Component" Grid.Row="3" VerticalAlignment="Center"/>
                    <Grid Grid.Column="1" Grid.Row="3">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="30"/>
                            <RowDefinition Height="30"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto" />
                            <ColumnDefinition Width="Auto"/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="ComponentNumber" />
                        <TextBox Grid.Column="1"
                                 TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding ComponentNumber, Mode=TwoWay}"
								 fui:Extensions.Watermark="Component Number"/>
                        <UIControls:WpfFilterCheckBox Grid.Row="1" VerticalAlignment="Center" AttributeName="ComponentName" />
                        <TextBox Grid.Column="1"
                                 Grid.Row="1"
                                 TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding ComponentName, Mode=TwoWay}"
								 fui:Extensions.Watermark="Component Name"/>
                        <UIControls:WpfComponentCatalog Grid.Column="2"
                                                        Grid.RowSpan="2"
                                                        VerticalAlignment="Center"
                                                        Name="ComponentCatalog"
                                                        SelectClicked="ComponentCatalog_SelectClicked"
                                                        SelectionDone="ComponentCatalog_SelectionDone"/>
                    </Grid>
					
                    <Label Content="Enum via Description" Grid.Row="4" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="4" Orientation="Horizontal" >
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Top" AttributeName="MyExampleEnum1" Margin="0,10,0,0" IsTabStop="False" />
                        <ComboBox Margin="2,0,0,0" 
                                  ItemsSource="{Binding Source={ngdDialog:EnumBindingSource {x:Type local:ExampleEnum}}}"
                                  SelectedItem="{Binding MyExampleEnum1, Mode=TwoWay}">
                        </ComboBox>
                    </StackPanel>
					
                    <Label Content="Enum via Image" Grid.Row="5" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="5" Orientation="Horizontal" >
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Top" AttributeName="MyExampleEnum2" Margin="0,10,0,0" IsTabStop="False" />
                        <ComboBox 
                            Margin="2,0,0,0" 
                            ItemsSource="{Binding Source={ngdDialog:EnumBindingSource {x:Type local:ExampleEnum}}}"
                            SelectedItem="{Binding MyExampleEnum2, Mode=TwoWay}">
                            <ComboBox.ItemTemplate>
                                <DataTemplate>
                                    <Image Source="{Binding Converter={StaticResource ImageConverter}}"/>
                                </DataTemplate>
                            </ComboBox.ItemTemplate>
                        </ComboBox>
                    </StackPanel>
                </Grid>
            </TabItem>
            <TabItem Header="Connection">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="19" />
                        <ColumnDefinition Width="63"/>
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="38" />
                        <RowDefinition Height="38" />
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>

                    <Label Content="Bolt Standard" Grid.Row="0" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,8,0,7"/>
                    <StackPanel Grid.Column="2" Grid.Row="0" Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltStandard"/>
                        <UIControls:WpfBoltCatalogStandard Width="160"
                                                           Height="23"
                                                           Name="BoltCatalogStandard"
                                                           SelectedItem="{Binding BoltStandard, Mode=TwoWay}"/>
                    </StackPanel>

                    <Label Content="Bolt Size" Grid.Row="1" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,7,0,8"/>
                    <StackPanel Grid.Column="2" Grid.Row="1" Orientation="Horizontal">
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltDiameter"/>
                        <UIControls:WpfBoltCatalogSize Width="160"
                                                       Height="23"
                                                       ItemsSource="{Binding ElementName=BoltCatalogStandard, Path=BoltSizes}"
                                                       SelectedItem="{Binding BoltDiameter, Mode=TwoWay}"/>
                    </StackPanel>

                    <Canvas Grid.Row="2" Grid.ColumnSpan="2" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="100,5,0,0">

                        <Image Source="pack://application:,,,/NgdPluginZeeConnect;component/Resources/images/ExampleImage.bmp" Stretch="None"/>

                        <StackPanel Orientation="Horizontal" 
                                    Canvas.Left="120" 
                                    Canvas.Top="-4">
                            <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltGage" />
                            <TextBox TextWrapping="Wrap" 
                                     Width="120" 
                                     Height="23" 
                                     VerticalAlignment="Center" 
                                     Text="{Binding BoltGage, Mode=TwoWay}"
									 fui:Extensions.Watermark="{Binding BoltGageWatermark}"/>
                        </StackPanel>

                        <StackPanel Orientation="Horizontal" 
                                    Canvas.Left="140" 
                                    Canvas.Top="41">
                            <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltOffset" />
                            <TextBox TextWrapping="Wrap" 
                                     Width="80" 
                                     Height="23" 
                                     VerticalAlignment="Center" 
                                     Text="{Binding BoltOffset, Mode=TwoWay}"
									 fui:Extensions.Watermark="Calculated"/>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" 
                                    Canvas.Left="140"
                                    Canvas.Top ="77" >
                            <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltRows" />
                            <TextBox TextWrapping="Wrap" 
                                     Width="40" 
                                     Height="23" 
                                     VerticalAlignment="Center" 
                                     Text="{Binding BoltRows, Mode=TwoWay}"
									 fui:Extensions.Watermark="None"/>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" 
                                    Canvas.Left="140"
                                    Canvas.Top="101">
                            <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltSpacing" />
                            <TextBox TextWrapping="Wrap" 
                                     Width="120" 
                                     Height="23" 
                                     VerticalAlignment="Center" 
                                     Text="{Binding BoltSpacing, Mode=TwoWay}"
									 fui:Extensions.Watermark="Calculated"/>
                        </StackPanel>
                    </Canvas>
                </Grid>
            </TabItem>
        </TabControl>
        <Image Source="pack://application:,,,/NgdPluginZeeConnect;component/Resources/images/CompanyLogoFull.png" 
            Grid.Row="1"    
            Stretch="None"
            HorizontalAlignment="Right" 
            VerticalAlignment="Top" 
            Margin="0,35,-610,0" Height="180"  >
            <Image.RenderTransform>
                <TransformGroup>
                    <ScaleTransform ScaleX="0.2" ScaleY="0.2"/>
                    <SkewTransform/>
                    <RotateTransform/>
                    <TranslateTransform/>
                </TransformGroup>
            </Image.RenderTransform>
        </Image>
    </Grid>
</tsd:PluginWindowBase>
