<tsd:PluginWindowBase x:Class="NgdPluginZeeConnect.NgdPluginZeeConnect"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
             xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
             xmlns:ngdDialog="clr-namespace:Ngd.Dialog;assembly=Ngd.Dialog"
             xmlns:fui="http://schemas.trimble.com/fusion"
			 xmlns:local="clr-namespace:NgdPluginZeeConnect"
             mc:Ignorable="d" 
             Title="NgdPluginZeeConnect"
             d:DesignHeight="435" d:DesignWidth="565"
               MinHeight="435" MinWidth="565">
    <d:UserControl.DataContext>
        <local:NgdPluginZeeConnectViewModel />
    </d:UserControl.DataContext>
    <Window.InputBindings>
        <KeyBinding Command="Help" Key="F1"/>
    </Window.InputBindings>
    <Window.CommandBindings>
        <CommandBinding Command="ApplicationCommands.Help" Executed="HelpExecuted" />
    </Window.CommandBindings>
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Fusion;component/Themes/Generic.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <local:EnumImageConverter x:Key="ImageConverter"/>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="5*"/>
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad x:Name="SaveLoad" HelpKeyword="NgdTeklaTools\NgdPluginZeeConnect" />
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="2"
            ApplyClicked="WpfOkApplyModifyGetOnOffCancel_ApplyClicked"
            OkClicked="WpfOkApplyModifyGetOnOffCancel_OkClicked"
            ModifyClicked="WpfOkApplyModifyGetOnOffCancel_ModifyClicked"
            GetClicked="WpfOkApplyModifyGetOnOffCancel_GetClicked"
            OnOffClicked="WpfOkApplyModifyGetOnOffCancel_OnOffClicked"
            CancelClicked="WpfOkApplyModifyGetOnOffCancel_CancelClicked"/>
        <TabControl Grid.Row="1">
            <TabItem Header="ClipSide">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*" />
                        <ColumnDefinition Width="4*"/>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                    </Grid.RowDefinitions>

                    <Label Content="Plate Thickness" VerticalAlignment="Center" />
                    <StackPanel Grid.Column="1" Orientation="Horizontal">
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="DisplayText"/>-->
                        <!--<TextBox TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center"
                                 Text="{Binding DisplayText, Mode=TwoWay}"
                                 fui:Extensions.Watermark="{Binding DisplayTextWatermark}"/>-->
                        <TextBox VerticalAlignment="Center" Width="120" Height="25" x:Name="Thickness" Text="{Binding Thickness, Mode=TwoWay}"/>
                    </StackPanel>

                    <Label Content="Weld size" Grid.Row="1" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="1" Orientation="Horizontal">
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="MyProfile" />-->
                        <TextBox Width="120" Height="25" x:Name="WeldSize" Text="{Binding Weldsize, Mode=TwoWay}"/>
                        <!--<UIControls:WpfProfileCatalog Name="MyProfileCatalog" 
							                          VerticalAlignment="Center"
							                          SelectClicked="MyProfileCatalog_SelectClicked"
							                          SelectionDone="MyProfileCatalog_SelectionDone"/>-->
                    </StackPanel>

                    <Label Content="No. of Bolts" Grid.Row="2" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="2" Orientation="Horizontal">
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="MyShape" />-->
                        <TextBox Width="120" Height="25" x:Name="NoOfBolt" Text="{Binding Boltactivation, Mode=TwoWay}"/>
                        <!--<UIControls:WpfShapeCatalog VerticalAlignment="Center"
                                                    Name="MyShapeCatalog"
                                                    SelectClicked="MyShapeCatalog_SelectClicked"
                                                    SelectionDone="MyShapeCatalog_SelectionDone"/>-->
                    </StackPanel>

                    <Label Content="Bolt Standard" Grid.Row="3" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="3" Orientation="Horizontal">
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="MyShape" />-->
                        <!--<TextBox Width="120" Height="20" x:Name="NocOfBolt" Text="{Binding Boltactivation, Mode=TwoWay}"/>-->
                        <UIControls:WpfBoltCatalogStandard SelectedIndex="0" Width="120" Height="25"
                                x:Name="BoltStandardCatalog1"
                                SelectedValue="{Binding BoltStandard, Mode=TwoWay}" 
                                SelectionChanged="BoltStandardCatalog1_SelectionChanged"/>
                        <!--<UIControls:WpfShapeCatalog VerticalAlignment="Center"
                                                    Name="MyShapeCatalog"
                                                    SelectClicked="MyShapeCatalog_SelectClicked"
                                                    SelectionDone="MyShapeCatalog_SelectionDone"/>-->
                    </StackPanel>
                    <!--<Grid Grid.Column="1" Grid.Row="3">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="30"/>
                            <RowDefinition Height="30"/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto" />
                            <ColumnDefinition Width="Auto"/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>
                        <UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="ComponentNumber" />
                        <TextBox Grid.Column="1"
                                 TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding ComponentNumber, Mode=TwoWay}"
								 fui:Extensions.Watermark="Component Number"/>
                        <UIControls:WpfFilterCheckBox Grid.Row="1" VerticalAlignment="Center" AttributeName="ComponentName" />
                        <TextBox Grid.Column="1"
                                 Grid.Row="1"
                                 TextWrapping="Wrap" 
                                 Width="120" 
                                 Height="23" 
                                 VerticalAlignment="Center" 
                                 Text="{Binding ComponentName, Mode=TwoWay}"
								 fui:Extensions.Watermark="Component Name"/>
                        <UIControls:WpfComponentCatalog Grid.Column="2"
                                                        Grid.RowSpan="2"
                                                        VerticalAlignment="Center"
                                                        Name="ComponentCatalog"
                                                        SelectClicked="ComponentCatalog_SelectClicked"
                                                        SelectionDone="ComponentCatalog_SelectionDone"/>
                    </Grid>-->

                    <Label Content="Bolt size" Grid.Row="4" VerticalAlignment="Center"/>
                    <StackPanel Grid.Column="1" Grid.Row="4" Orientation="Horizontal" >
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Top" AttributeName="MyExampleEnum1" Margin="0,10,0,0" IsTabStop="False" />-->
                        <UIControls:WpfBoltCatalogSize SelectedIndex="0" Width="120" Height="25"
                    
                                x:Name="BoltSize1" 
                                SelectedItem="{Binding BoltDiameter, Mode=TwoWay}" 
                                ItemsSource="{Binding ElementName=BoltStandardCatalog1, Path=BoltSizes}" />
                    </StackPanel>
                    <Canvas Grid.Column="1" Grid.Row="5" >
                        <Image x:Name="Plate_side" Source="Plate side Attribute.png" Height="182" Canvas.Left="119" Width="327" Canvas.Top="-162"  />
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Top" AttributeName="MyExampleEnum1" Margin="0,10,0,0" IsTabStop="False" />-->
                    </Canvas>



                </Grid>
            </TabItem>
            <TabItem Header="Extension Side">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*" />
                        <!--<ColumnDefinition Width=""/>-->
                        <ColumnDefinition Width="4*"/>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40" />
                        <RowDefinition Height="40"/>
                        <RowDefinition Height="40"/>
                        <RowDefinition Height="40"/>
                    </Grid.RowDefinitions>

                    <Label Content="Extension" Grid.Row="0" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,8,0,7"/>
                    <StackPanel Grid.Column="2" Grid.Row="0" Orientation="Horizontal">
                        <TextBox Width="120" Height="25" x:Name="Extension_Value" Text="{Binding Extension, Mode=TwoWay}"/>
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltStandard"/>
                        <UIControls:WpfBoltCatalogStandard Width="160"
                                                           Height="23"
                                                           Name="BoltCatalogStandard"
                                                           SelectedItem="{Binding BoltStandard, Mode=TwoWay}"/>-->
                    </StackPanel>

                    <Label Content="End Margin" Grid.Row="1" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,7,0,8"/>
                    <StackPanel Grid.Column="2" Grid.Row="1" Orientation="Horizontal">
                        <TextBox Width="120" Height="25" x:Name="marginEndBolt" Text="{Binding Margin, Mode=TwoWay}"/>
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltDiameter"/>
                        <UIControls:WpfBoltCatalogSize Width="160"
                                                       Height="23"
                                                       ItemsSource="{Binding ElementName=BoltCatalogStandard, Path=BoltSizes}"
                                                       SelectedItem="{Binding BoltDiameter, Mode=TwoWay}"/>-->
                    </StackPanel>
                    <Label Content="End Margin" Grid.Row="2" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,7,0,8"/>
                    <StackPanel Grid.Column="2" Grid.Row="2" Orientation="Horizontal">
                        <UIControls:WpfBoltCatalogStandard SelectedIndex="0" Width="120" Height="25"
                                x:Name="BoltStandardCatalog2"
                                Margin="2 0 0 0" 
                                SelectedValue="{Binding EBoltstandard, Mode=TwoWay}"
                                SelectionChanged="BoltStandardCatalog2_SelectionChanged"/>
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltDiameter"/>
                        <UIControls:WpfBoltCatalogSize Width="160"
                                                       Height="23"
                                                       ItemsSource="{Binding ElementName=BoltCatalogStandard, Path=BoltSizes}"
                                                       SelectedItem="{Binding BoltDiameter, Mode=TwoWay}"/>-->
                    </StackPanel>
                    <Label Content="End Margin" Grid.Row="3" VerticalAlignment="Center" Grid.ColumnSpan="2" Margin="0,7,0,8"/>
                    <StackPanel Grid.Column="2" Grid.Row="3" Orientation="Horizontal">
                        <UIControls:WpfBoltCatalogSize SelectedIndex="0" Width="120" Height="25"
                    
                                x:Name="BoltSize2" 
                                SelectedItem="{Binding EBoltsize, Mode=TwoWay}" 
                                ItemsSource="{Binding ElementName=BoltStandardCatalog2, Path=BoltSizes}" />
                        <!--<UIControls:WpfFilterCheckBox VerticalAlignment="Center" AttributeName="BoltDiameter"/>
                        <UIControls:WpfBoltCatalogSize Width="160"
                                                       Height="23"
                                                       ItemsSource="{Binding ElementName=BoltCatalogStandard, Path=BoltSizes}"
                                                       SelectedItem="{Binding BoltDiameter, Mode=TwoWay}"/>-->
                    </StackPanel>
                    <Canvas>
                        <Image Source="Extension side Attribute.png" Canvas.Left="254" Canvas.Top="62" Height="153" Width="264">

                        </Image>
                    </Canvas>



                </Grid>
            </TabItem>
        </TabControl>
        <Image Source="pack://application:,,,/NgdPluginZeeConnect;component/Resources/images/CompanyLogoFull.png" 
            Grid.Row="1"    
            Stretch="None"
            HorizontalAlignment="Right" 
            VerticalAlignment="Top" 
            Margin="0,35,-610,0" Height="180"  >
            <Image.RenderTransform>
                <TransformGroup>
                    <ScaleTransform ScaleX="0.2" ScaleY="0.2"/>
                    <SkewTransform/>
                    <RotateTransform/>
                    <TranslateTransform/>
                </TransformGroup>
            </Image.RenderTransform>
        </Image>
    </Grid>
</tsd:PluginWindowBase>
